name: recipe_card_stack
description: A smooth, swipeable stacked-card widget with tap-to-focus, infinite looping and customizable card layouts.


version: 0.0.3

repository: https://github.com/marcoazeem/recipe_card_stack
issue_tracker: https://github.com/marcoazeem/recipe_card_stack/issues

topics:
  - cards
  - swipe
  - stack
  - ui
  - selector

license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
